"""
Data Ingestion Service — loads and caches pre-computed data grids.

Serves as the single source-of-truth for:
  - Iceberg CSV (USNIC / BYU)
  - SIC JSON grid (NSIDC / physics)
  - Wind JSON grid (Open-Meteo ERA5 / climatology)
  - Polar Routes GeoJSON (COMNAP corridors)

Triggers download_data.py automatically if data is older than 24h.
"""
from __future__ import annotations

import asyncio
import csv
import json
import math
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from loguru import logger


# ── Paths (resolved relative to backend/ root) ─────────────────────────────────

def _data_dir() -> Path:
    return Path(__file__).parent.parent.parent / "data"


def _scripts_dir() -> Path:
    return Path(__file__).parent.parent.parent / "scripts"


INGEST_MAX_AGE_HOURS = 24.0


# ══════════════════════════════════════════════════════════════════════════════
# Ingestion Service
# ══════════════════════════════════════════════════════════════════════════════

class IngestionService:
    """
    Loads and serves pre-computed data grids generated by download_data.py.
    Automatically re-triggers ingestion if data is stale (>24h).
    """

    def __init__(self):
        self._data_dir = _data_dir()
        self._data_dir.mkdir(parents=True, exist_ok=True)
        self._icebergs: list[dict] = []
        self._sic_cells: list[dict] = []
        self._wind_cells: list[dict] = []
        self._routes: list[dict] = []
        self._loaded = False
        self._last_load: Optional[datetime] = None

    # ── Public accessors ───────────────────────────────────────────────────────

    def get_icebergs(self) -> list[dict]:
        return self._icebergs

    def get_sic_cells(self) -> list[dict]:
        return self._sic_cells

    def get_wind_cells(self) -> list[dict]:
        return self._wind_cells

    def get_routes(self) -> list[dict]:
        return self._routes

    def status(self) -> dict:
        last_run_file = self._data_dir / ".last_ingestion"
        last_run = None
        age_hours = None
        if last_run_file.exists():
            ts = float(last_run_file.read_text().strip())
            last_run = datetime.fromtimestamp(ts, tz=timezone.utc)
            age_hours = (datetime.now(tz=timezone.utc) - last_run).total_seconds() / 3600

        return {
            "last_run": last_run,
            "icebergs_loaded": len(self._icebergs),
            "sic_cells_loaded": len(self._sic_cells),
            "wind_cells_loaded": len(self._wind_cells),
            "routes_loaded": len(self._routes),
            "gebco_available": (self._data_dir / "gebco.nc").exists(),
            "data_age_hours": round(age_hours, 2) if age_hours is not None else None,
        }

    # ── Startup Loading ────────────────────────────────────────────────────────

    async def initialize(self) -> None:
        """
        Called on FastAPI startup.
        Loads existing data, then triggers ingestion if stale.
        """
        self._load_all_from_disk()

        if self._is_stale():
            logger.info("Data is stale – triggering background ingestion …")
            asyncio.create_task(self._run_ingestion_background())
        else:
            logger.info(
                "Ingestion data loaded: {} icebergs, {} SIC cells, {} wind cells, {} routes",
                len(self._icebergs), len(self._sic_cells), len(self._wind_cells), len(self._routes)
            )

    async def _run_ingestion_background(self) -> None:
        """Run download_data.py --all in a subprocess without blocking the event loop."""
        script = _scripts_dir() / "download_data.py"
        python = sys.executable
        try:
            proc = await asyncio.create_subprocess_exec(
                python, str(script), "--all",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await proc.communicate()
            if proc.returncode == 0:
                logger.info("Ingestion complete. Reloading data …")
                self._load_all_from_disk()
            else:
                logger.error("Ingestion failed (exit {}): {}", proc.returncode, stderr.decode())
        except Exception as exc:
            logger.error("Ingestion subprocess error: {}", exc)

    # ── Data Loaders ───────────────────────────────────────────────────────────

    def _load_all_from_disk(self) -> None:
        self._icebergs = self._load_iceberg_csv()
        self._sic_cells = self._load_json_cells("sic_grid.json", key="cells")
        self._wind_cells = self._load_json_cells("wind_grid.json", key="cells")
        self._routes = self._load_routes_geojson()
        self._loaded = True
        self._last_load = datetime.now(tz=timezone.utc)

    def _load_iceberg_csv(self) -> list[dict]:
        path = self._data_dir / "iceberg_tracks.csv"
        if not path.exists():
            logger.warning("iceberg_tracks.csv not found – using empty list")
            return []
        try:
            rows = []
            with open(path) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    rows.append({k: _auto_cast(v) for k, v in row.items()})
            logger.debug("Loaded {} icebergs from CSV", len(rows))
            return rows
        except Exception as exc:
            logger.error("Failed to load iceberg CSV: {}", exc)
            return []

    def _load_json_cells(self, filename: str, key: str = "cells") -> list[dict]:
        path = self._data_dir / filename
        if not path.exists():
            return []
        try:
            with open(path) as f:
                data = json.load(f)
            cells = data.get(key, [])
            logger.debug("Loaded {} cells from {}", len(cells), filename)
            return cells
        except Exception as exc:
            logger.error("Failed to load {}: {}", filename, exc)
            return []

    def _load_routes_geojson(self) -> list[dict]:
        path = self._data_dir / "polar_routes.geojson"
        if not path.exists():
            return []
        try:
            with open(path) as f:
                geojson = json.load(f)
            features = geojson.get("features", [])
            logger.debug("Loaded {} polar route features", len(features))
            return features
        except Exception as exc:
            logger.error("Failed to load polar_routes.geojson: {}", exc)
            return []

    def _is_stale(self) -> bool:
        marker = self._data_dir / ".last_ingestion"
        if not marker.exists():
            return True
        try:
            ts = float(marker.read_text().strip())
            age_s = (datetime.now(tz=timezone.utc).timestamp() - ts)
            return age_s > INGEST_MAX_AGE_HOURS * 3600
        except Exception:
            return True


# ── Route Segment Risk Scorer ──────────────────────────────────────────────────

class RouteRiskScorer:
    """
    Scores each 50km segment of every polar route corridor using:
      - SIC grid (nearest cell interpolation)
      - Iceberg proximity (haversine distance)
      - Bathymetry (via BathymetryService)
    """

    def score_routes(
        self,
        routes: list[dict],
        sic_cells: list[dict],
        icebergs: list[dict],
    ) -> list[dict]:
        """Returns list of scored route features."""
        sic_index = self._build_sic_index(sic_cells)
        iceberg_positions = [(float(b.get("lat", 0)), float(b.get("lon", 0))) for b in icebergs]

        scored_routes = []
        for feature in routes:
            segments = feature.get("segments", [])
            scored_segments = []
            route_risks = []

            for seg in segments:
                clat = float(seg["center_lat"])
                clon = float(seg["center_lon"])

                # 1. Ice concentration
                ice_conc = self._nearest_sic(clat, clon, sic_index)
                ice_risk = min(1.0, ice_conc / 0.8)

                # 2. Iceberg proximity
                prox_km = self._min_iceberg_distance(clat, clon, iceberg_positions)
                if prox_km is None:
                    berg_risk = 0.0
                elif prox_km < 50:
                    berg_risk = 1.0
                elif prox_km < 200:
                    berg_risk = 1.0 - (prox_km - 50) / 150
                else:
                    berg_risk = 0.0

                # 3. Bathymetry risk (fast estimate without loading GEBCO)
                from app.services.bathymetry_service import get_bathymetry
                bathy_risk = get_bathymetry().depth_risk(clat, clon)

                # 4. Composite risk score (40% ice, 30% berg, 20% bathy, 10% baseline weather)
                total_risk = (0.40 * ice_risk + 0.30 * berg_risk + 0.20 * bathy_risk + 0.10 * 0.1)
                total_risk = round(min(1.0, total_risk), 4)
                route_risks.append(total_risk)

                # Risk level
                if total_risk < 0.25:
                    risk_level = "safe"
                elif total_risk < 0.60:
                    risk_level = "moderate"
                else:
                    risk_level = "high"

                scored_segments.append({
                    **seg,
                    "risk_level": risk_level,
                    "risk_score": total_risk,
                    "ice_concentration": round(ice_conc, 4),
                    "iceberg_proximity_km": round(prox_km, 1) if prox_km is not None else None,
                })

            # Overall route risk = 90th percentile of segment risks
            if route_risks:
                route_risks_sorted = sorted(route_risks)
                p90_idx = min(len(route_risks_sorted) - 1, int(len(route_risks_sorted) * 0.9))
                overall_risk_score = route_risks_sorted[p90_idx]
            else:
                overall_risk_score = 0.0

            if overall_risk_score < 0.25:
                overall_risk = "safe"
            elif overall_risk_score < 0.60:
                overall_risk = "moderate"
            else:
                overall_risk = "high"

            props = feature.get("properties", {})
            scored_routes.append({
                "route_id": props.get("route_id", ""),
                "name": props.get("name", ""),
                "route_type": props.get("route_type", "supply"),
                "distance_km": props.get("distance_km", 0),
                "typical_vessel": props.get("typical_vessel", "supply"),
                "overall_risk": overall_risk,
                "overall_risk_score": round(overall_risk_score, 4),
                "segments": scored_segments,
                "waypoints": self._extract_waypoints(feature),
                "geometry": feature.get("geometry", {}),
            })

        return scored_routes

    @staticmethod
    def _build_sic_index(cells: list[dict]) -> dict[tuple, float]:
        """Build coarse 0.5° grid index for fast SIC lookups."""
        index = {}
        for c in cells:
            key = (round(float(c["lat"]) * 2) / 2, round(float(c["lon"]) * 2) / 2)
            index[key] = float(c.get("concentration", 0.0))
        return index

    @staticmethod
    def _nearest_sic(lat: float, lon: float, index: dict) -> float:
        best_key = (round(lat * 2) / 2, round(lon * 2) / 2)
        if best_key in index:
            return index[best_key]
        # Search neighbouring cells
        for dlat in [-0.5, 0.0, 0.5]:
            for dlon in [-0.5, 0.0, 0.5]:
                k = (round((lat + dlat) * 2) / 2, round((lon + dlon) * 2) / 2)
                if k in index:
                    return index[k]
        return 0.0

    @staticmethod
    def _min_iceberg_distance(lat: float, lon: float, icebergs: list[tuple]) -> Optional[float]:
        if not icebergs:
            return None
        phi1 = math.radians(lat)
        best = float("inf")
        for blat, blon in icebergs:
            dphi = math.radians(blat - lat)
            dlam = math.radians(blon - lon)
            a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(math.radians(blat)) * math.sin(dlam / 2) ** 2
            dist = 2 * 6371.0 * math.asin(math.sqrt(a))
            if dist < best:
                best = dist
        return best if best < float("inf") else None

    @staticmethod
    def _extract_waypoints(feature: dict) -> list[dict]:
        coords = feature.get("geometry", {}).get("coordinates", [])
        return [{"lat": c[1], "lon": c[0]} for c in coords]


# ── Auto-type helper ──────────────────────────────────────────────────────────

def _auto_cast(value: str) -> Any:
    """Try to cast CSV string to int, float, or leave as str."""
    try:
        return int(value)
    except (ValueError, TypeError):
        pass
    try:
        return float(value)
    except (ValueError, TypeError):
        pass
    return value


# ── Singletons ─────────────────────────────────────────────────────────────────

_ingestion_instance: Optional[IngestionService] = None
_scorer_instance: Optional[RouteRiskScorer] = None


def get_ingestion() -> IngestionService:
    global _ingestion_instance
    if _ingestion_instance is None:
        _ingestion_instance = IngestionService()
    return _ingestion_instance


def get_route_scorer() -> RouteRiskScorer:
    global _scorer_instance
    if _scorer_instance is None:
        _scorer_instance = RouteRiskScorer()
    return _scorer_instance
