"""Ocean currents route: /ocean/currents — real-time global ocean current vectors for Cesium Wind Layer."""
from __future__ import annotations

import json
from pathlib import Path
from fastapi import APIRouter
from loguru import logger
from fastapi.responses import JSONResponse

router = APIRouter(prefix="/ocean", tags=["Ocean Currents"])

@router.get("/currents")
async def get_ocean_currents():
    """
    Return a global ocean current vector grid (U and V) formatted for cesium-wind-layer.
    Reads directly from data/currents_grid.json generated by process_currents.py via Copernicus.
    """
    json_path = Path("data/currents_grid.json")
    
    if json_path.exists():
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            logger.info(f"Served ocean currents from {json_path}")
            return JSONResponse(content=data)
        except Exception as e:
            logger.error(f"Failed to read {json_path}: {e}")
            
    # Fallback if file doesn't exist
    logger.warning("currents_grid.json not found, returning 404")
    return JSONResponse(content={"error": "Ocean currents grid not generated yet."}, status_code=404)
