"""Wind field route: /wind/field — real-time global wind vectors for Cesium Wind Layer."""
from __future__ import annotations

import json
from pathlib import Path
from fastapi import APIRouter
from loguru import logger
from fastapi.responses import JSONResponse

router = APIRouter(prefix="/wind", tags=["Wind Field"])

@router.get("/field")
async def get_wind_field():
    """
    Return a global wind vector grid (U and V) formatted for cesium-wind-layer.
    Reads directly from data/wind_grid.json generated by process_grib.py via Herbie.
    """
    json_path = Path("data/wind_grid.json")
    
    if json_path.exists():
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            logger.info(f"Served wind field from {json_path}")
            return JSONResponse(content=data)
        except Exception as e:
            logger.error(f"Failed to read {json_path}: {e}")
            
    # Fallback if file doesn't exist
    logger.warning("wind_grid.json not found, returning 404")
    return JSONResponse(content={"error": "Wind grid not generated yet."}, status_code=404)
