import React, { useEffect, useRef } from 'react';
import { WindLayer } from 'cesium-wind-layer';
import type { Viewer } from 'cesium';

interface WindLayerResiumProps {
  viewer: Viewer;
  /** The JSON data generated by backend/scripts/process_grib.py */
  data: any;
  show: boolean;
  options?: any;
}

/**
 * Component that wraps the raw `cesium-wind-layer` plugin.
 * Takes the parent `viewer` as a prop and instantiates the GPU-accelerated particle animation layer.
 */
export const WindLayerResium: React.FC<WindLayerResiumProps> = ({ viewer, data, show, options }) => {
  const windLayerRef = useRef<WindLayer | null>(null);

  useEffect(() => {
    // We can only initialize if we have a valid viewer and data
    if (!viewer || !data) return;

    let processedData = data;

    // If data is the classic GFS JSON array, parse it into WindData
    if (Array.isArray(data) && data.length === 2 && data[0].header) {
      const uRec = data[0];
      const vRec = data[1];
      processedData = {
        u: { array: new Float32Array(uRec.data) },
        v: { array: new Float32Array(vRec.data) },
        width: uRec.header.nx,
        height: uRec.header.ny,
        bounds: {
          west: uRec.header.lo1,
          south: Math.min(uRec.header.la1, uRec.header.la2),
          east: uRec.header.lo2,
          north: Math.max(uRec.header.la1, uRec.header.la2),
        }
      };
    } else if (Array.isArray(data) && data.length !== 2) {
        return; // Wait for valid data
    }

    const defaultOptions = {
      windOptions: {
        // Particle styling and animation parameters (earth.nullschool style)
        colorScale: [
          'rgb(36,104, 180)',
          'rgb(60,157, 194)',
          'rgb(128,205,193 )',
          'rgb(151,218,168 )',
          'rgb(198,231,181)',
          'rgb(238,247,217)',
          'rgb(255,238,159)',
          'rgb(252,217,125)',
          'rgb(255,182,100)',
          'rgb(252,150,75)',
          'rgb(250,112,52)',
          'rgb(245,64,32)',
          'rgb(237,45,28)',
          'rgb(220,24,32)',
          'rgb(180,0,35)'
        ],
        velocityScale: 0.01,
        paths: 5000,
        lineWidth: 2,
        generateParticleOption: false,
      }
    };

    const finalOptions = options ? { windOptions: { ...defaultOptions.windOptions, ...options.windOptions } } : defaultOptions;

    // Initialize the WindLayer
    const windLayer = new WindLayer(viewer, processedData, finalOptions);

    windLayerRef.current = windLayer;

    // Cleanup: destroy the layer when component unmounts or data changes
    return () => {
      if (windLayerRef.current && viewer && !viewer.isDestroyed()) {
        windLayerRef.current.destroy();
        windLayerRef.current = null;
      }
    };
  }, [viewer, data]);

  // Handle toggling visibility without recreating the layer
  useEffect(() => {
    if (windLayerRef.current) {
      windLayerRef.current.show = show;
    }
  }, [show]);

  // This component manages its own render via Cesium JS manipulation, 
  // so it returns null (no React DOM elements).
  return null;
};
