import React, { useEffect, useRef } from 'react';
import { useCesium } from 'resium';
import { WindLayer } from 'cesium-wind-layer';
import type { Viewer } from 'cesium';

interface WindLayerResiumProps {
  /** The JSON data generated by backend/scripts/parse_grib.py */
  data: any;
  show: boolean;
}

/**
 * Resium component that wraps the raw `cesium-wind-layer` plugin.
 * Uses the `useCesium` hook to access the parent `<Viewer>` context
 * and instantiates the GPU-accelerated particle animation layer.
 */
export const WindLayerResium: React.FC<WindLayerResiumProps> = ({ data, show }) => {
  // Extract the Cesium viewer from the Resium context
  const { viewer } = useCesium();
  const windLayerRef = useRef<WindLayer | null>(null);

  useEffect(() => {
    // We can only initialize if we have a valid viewer and data
    if (!viewer || !data) return;

    // Initialize the WindLayer
    const windLayer = new WindLayer(viewer, data, {
      windOptions: {
        // Particle styling and animation parameters (earth.nullschool style)
        colorScale: [
          'rgb(36,104, 180)',
          'rgb(60,157, 194)',
          'rgb(128,205,193 )',
          'rgb(151,218,168 )',
          'rgb(198,231,181)',
          'rgb(238,247,217)',
          'rgb(255,238,159)',
          'rgb(252,217,125)',
          'rgb(255,182,100)',
          'rgb(252,150,75)',
          'rgb(250,112,52)',
          'rgb(245,64,32)',
          'rgb(237,45,28)',
          'rgb(220,24,32)',
          'rgb(180,0,35)'
        ],
        velocityScale: 0.01,
        paths: 5000,
        lineWidth: 2,
        generateParticleOption: false,
      }
    });

    windLayerRef.current = windLayer;

    // Cleanup: destroy the layer when component unmounts or data changes
    return () => {
      if (windLayerRef.current && viewer && !viewer.isDestroyed()) {
        windLayerRef.current.destroy();
        windLayerRef.current = null;
      }
    };
  }, [viewer, data]);

  // Handle toggling visibility without recreating the layer
  useEffect(() => {
    if (windLayerRef.current) {
      windLayerRef.current.show = show;
    }
  }, [show]);

  // This component manages its own render via Cesium JS manipulation, 
  // so it returns null (no React DOM elements).
  return null;
};
